image: registry.quiqup.com/backend/docker-realtimeex-deploy:elixir-1-4-5

stages:
  - test

test:
  stage: test
  variables:
    MIX_ENV: test
  script:
    - mix hex.organization auth quiqup --key $HEX_KEY
    - mix local.hex --force && mix local.rebar --force
    - mix do deps.get, deps.compile
    - mix do compile --warnings-as-errors
    - mix test
  tags:
    - docker
  except:
    - tags
